# Generated by Django 3.0.2 on 2020-01-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_problem_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='lda_label',
            field=models.CharField(default='N/A', max_length=3),
        ),
        migrations.AddField(
            model_name='problem',
            name='pat_label',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='problem',
            name='w2v_label',
            field=models.CharField(default='N/A', max_length=3),
        ),
        migrations.AlterField(
            model_name='problem',
            name='url',
            field=models.CharField(max_length=999),
        ),
    ]
